default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: juanitofatas_development

test:
  <<: *default
  database: juanitofatas_test

production:
  <<: *default
  database: juanitofatas_production
  username: juanitofatas
  password: <%= ENV["JUANITOFATAS_DATABASE_PASSWORD"] %>
